name = "dailyhot-api-pages"
pages_build_output_dir = "./dist"
compatibility_date = "2026-07-14"
compatibility_flags = ["nodejs_compat"]

[vars]
CACHE_TTL = "3600"
REQUEST_TIMEOUT = "6000"
ALLOWED_DOMAIN = "https://haotab.link,https://www.haotab.link"
ALLOWED_HOST = ""
DISALLOW_ROBOT = "true"
USE_LOG_FILE = "false"
RSS_MODE = "false"
FILTER_WEIBO_ADVERTISEMENT = "false"

[[kv_namespaces]]
binding = "CACHE"
id = "5eac08c474874c059536ab6b7a13a376"
